name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"                   # Hide OS stats
          SHOW_PROJECTS: "False"             # Hide project stats (removes the "This week I spent my time on ..." line)
          SHOW_TOTAL_CODE_TIME: "False"      # Hide total code time (optional)
          SHOW_PROFILE_VIEWS: "False"        # Hide profile views (optional)
